CREATE SCHEMA USE_DIYNOVO;

USE USE_DIYNOVO;

CREATE TABLE USR_USUARIO (
  USR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USR_NOME VARCHAR(20) NOT NULL,
  USR_SENHA VARCHAR(50) NOT NULL,
  USR_DATAINCLUSAO DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT USR_USUARIO_PK PRIMARY KEY (USR_ID),
  CONSTRAINT USR_NOME_UK UNIQUE KEY (USR_NOME)
);

CREATE TABLE TPO_TIPO (
    TPO_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TPO_NOME VARCHAR(30) NOT NULL UNIQUE,
    TPO_DATAINCLUSAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT TPO_TIPO_PK PRIMARY KEY (TPO_ID)
);

CREATE TABLE MTR_MATERIAL (
    MTR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MTR_NOME VARCHAR(30) NOT NULL,
    MTR_DESCRICAO VARCHAR(50) NOT NULL,
    TPO_ID BIGINT UNSIGNED NOT NULL,
    MTR_DATAINCLUSAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT MTR_MATERIAL_PK PRIMARY KEY (MTR_ID),
    FOREIGN KEY (TPO_ID)
        REFERENCES TPO_TIPO (TPO_ID)
        ON DELETE RESTRICT
);

CREATE TABLE RCT_RECEITA (
	RCT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	RCT_NOME VARCHAR(50) NOT NULL,
    RCT_DESCRICAO VARCHAR(200) NOT NULL,
    RCT_DATAINCLUSAO DATETIME DEFAULT CURRENT_TIMESTAMP,
	USR_ID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT RCT_RECEITA_PK PRIMARY KEY (RCT_ID),
	FOREIGN KEY (USR_ID)
        REFERENCES USR_USUARIO (USR_ID)
        ON DELETE RESTRICT
);

CREATE TABLE RCM_RECEITAMATERIAL (
    MTR_ID BIGINT UNSIGNED NOT NULL,
	RCT_ID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT RCM_RECEITAMATERIAL_PK PRIMARY KEY (MTR_ID, RCT_ID),
    RCM_DATAINCLUSAO DATETIME DEFAULT CURRENT_TIMESTAMP
);
