CREATE SCHEMA USE_DIYNOVO;

USE USE_DIYNOVO;

CREATE TABLE USR_USUARIO (
  USR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USR_NOME VARCHAR(20) NOT NULL,
  USR_SENHA VARCHAR(50) NOT NULL,
  CONSTRAINT USR_USUARIO_PK PRIMARY KEY (USR_ID),
  CONSTRAINT USR_NOME_UK UNIQUE KEY (USR_NOME)
);

CREATE TABLE TPO_TIPO (
    TPO_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TPO_NOME VARCHAR(30) NOT NULL,
    CONSTRAINT TPO_TIPO_PK PRIMARY KEY (TPO_ID)
);

CREATE TABLE MTR_MATERIAL (
    MTR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MTR_NOME VARCHAR(30) NOT NULL,
    MTR_DESCRICAO VARCHAR(50) NOT NULL,
    TPO_ID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT MTR_MATERIAL_PK PRIMARY KEY (MTR_ID),
    FOREIGN KEY (TPO_ID)
        REFERENCES TPO_TIPO (TPO_ID)
        ON DELETE RESTRICT ON UPDATE CASCADE
);