CREATE SCHEMA USE_DIYNOVO2;

USE USE_DIYNOVO2;

CREATE TABLE USR_USUARIO (
  USR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USR_NOME VARCHAR(20) NOT NULL,
  USR_SENHA VARCHAR(50) NOT NULL,
  USR_DATAINCLUSAO DATETIME DEFAULT NOW(),
  CONSTRAINT USR_USUARIO_PK PRIMARY KEY (USR_ID),
  CONSTRAINT USR_NOME_UK UNIQUE KEY (USR_NOME)
);

CREATE TABLE AUT_AUTORIZACAO (
  AUT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  AUT_NOME VARCHAR(20) NOT NULL,
  AUT_DATAINCLUSAO DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT AUT_AUTORIZACAO_PK PRIMARY KEY (AUT_ID),
  CONSTRAINT AUT_NOME_UK UNIQUE KEY (AUT_NOME)
);

CREATE TABLE UAU_USUARIO_AUTORIZACAO (
  USR_ID BIGINT UNSIGNED NOT NULL,
  AUT_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (USR_ID, AUT_ID),
  FOREIGN KEY UAU_USUARIO_FK (USR_ID) REFERENCES USR_USUARIO (USR_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY UAU_AUTORIZACAO_FK (AUT_ID) REFERENCES AUT_AUTORIZACAO (AUT_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE TPO_TIPO (
    TPO_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TPO_NOME VARCHAR(30) NOT NULL UNIQUE,
    TPO_DATAINCLUSAO DATETIME DEFAULT NOW(),
    CONSTRAINT TPO_TIPO_PK PRIMARY KEY (TPO_ID)
);

CREATE TABLE MTR_MATERIAL (
    MTR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MTR_NOME VARCHAR(30) NOT NULL,
    MTR_DESCRICAO VARCHAR(50) NOT NULL,
    TPO_ID BIGINT UNSIGNED NOT NULL,
    MTR_DATAINCLUSAO DATETIME DEFAULT NOW(),
    CONSTRAINT MTR_MATERIAL_PK PRIMARY KEY (MTR_ID),
    FOREIGN KEY (TPO_ID)
        REFERENCES TPO_TIPO (TPO_ID)
        ON DELETE RESTRICT
);

CREATE TABLE RCT_RECEITA (
	RCT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	RCT_NOME VARCHAR(50) NOT NULL,
    RCT_DESCRICAO VARCHAR(200) NOT NULL,
    RCT_DATAINCLUSAO DATETIME DEFAULT NOW(),
	USR_ID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT RCT_RECEITA_PK PRIMARY KEY (RCT_ID),
	FOREIGN KEY (USR_ID)
        REFERENCES USR_USUARIO (USR_ID)
        ON DELETE RESTRICT
);

CREATE TABLE RCM_RECEITAMATERIAL (
    MTR_ID BIGINT UNSIGNED NOT NULL,
	RCT_ID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT RCM_RECEITAMATERIAL_PK PRIMARY KEY (MTR_ID, RCT_ID),
    RCM_DATAINCLUSAO DATETIME DEFAULT NOW()
);
